/**
 * Runtime image manifest — generated by `pnpm images:runtime` from
 * assets-source/. Widths and ratios are authoritative; the React side
 * builds srcset from this map and never hard-codes raw paths.
 */

export type ImageBucket = 'quiz' | 'results' | 'landing'

export interface ImageVariant {
  w: number
  h: number
  bytes: number
}

export interface ImageEntry {
  ratio: '16/9' | '4/5'
  widths: readonly number[]
  webp: Record<string, ImageVariant>
  jpeg: Record<string, ImageVariant>
}

export interface RuntimeImageManifest {
  quiz: Record<string, ImageEntry>
  results: Record<string, ImageEntry>
  landing: Record<string, ImageEntry>
  widths: readonly number[]
}

import manifestJson from '../../public/optimized/manifest.json'

export const RUNTIME_IMAGE_MANIFEST: RuntimeImageManifest =
  manifestJson as unknown as RuntimeImageManifest

/** Build a webp/jpeg srcset string for an entry. */
export function buildSrcSet(
  entry: ImageEntry,
  bucket: ImageBucket,
  name: string,
  ext: 'webp' | 'jpg',
): string {
  return entry.widths
    .map((w) => `/optimized/${bucket}/${name}-${w}.${ext} ${w}w`)
    .join(', ')
}

/** Default sizes attribute tuned for an answer card on the 480/600 column. */
export const ANSWER_CARD_SIZES = '(max-width: 480px) calc(100vw - 32px), 480px'

/** Result hero: full column width. */
export const RESULT_HERO_SIZES = '(max-width: 480px) calc(100vw - 32px), 480px'