import { results } from './results.js'
import type { Question, Quiz } from '../../../features/quiz/schema.js'

/**
 * Music90s content — 42 question BANK, 18 per run via stratified selector.
 * Content policy:
 * - short lyric excerpts are allowed when needed for recognition/nostalgia;
 * - no full verses, choruses, or long contiguous lyric passages;
 * - lyric questions must not dominate the quiz;
 * - no album art or rehosted third-party media.
 *
 * Answer ids (a/b/c/d) are reused across questions: identity is compound (questionId, answerId).
 * Bank is sampled per attempt via selectMusic90Questions(bank, 18, rng) — stable within run.
 */

export const MUSIC90_QUESTIONS_PER_RUN = 18

export type Music90QuestionCategory = 'song' | 'artist' | 'clip' | 'mtv' | 'culture' | 'rebus'

export const questions: Question[] = [
  {
    id: 'm1',
    category: 'emoji',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какой хит зашифрован?\n\n💌 ➡️ 📭 😔 ❤️',
    correctAnswerId: 'a',
    feedback: {
      correct: 'В точку!',
      wrong: 'Эх, мимо.',
    },
    answers: [
      { id: 'a', title: '«Крошка моя»' },
      { id: 'b', title: '«Алёшка»' },
      { id: 'c', title: '«Он тебя целует»' },
      { id: 'd', title: '«Чужие губы»' },
    ],
  },
  {
    id: 'm2',
    category: 'music-video',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Чей томный взгляд и расстёгнутая рубашка в клипе «Позови меня в ночи» сводили с ума девчонок по всей стране?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Зачёт!',
      wrong: 'Не-а, не то.',
    },
    answers: [
      { id: 'a', title: 'Кай Метов' },
      { id: 'b', title: 'Влад Сташевский' },
      { id: 'c', title: 'Дмитрий Маликов' },
      { id: 'd', title: 'Женя Белоусов' },
    ],
  },
  {
    id: 'm3',
    category: 'artist-history',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Кто до сольной карьеры пела в группе «Комбинация»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'В яблочко!',
      wrong: 'Чуть-чуть не туда.',
    },
    answers: [
      { id: 'a', title: 'Лада Дэнс' },
      { id: 'b', title: 'Алёна Апина' },
      { id: 'c', title: 'Татьяна Овсиенко' },
      { id: 'd', title: 'Наталья Ветлицкая' },
    ],
  },
  {
    id: 'm4',
    category: 'song-recognition',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой хит конца 90-х заставлял смотреть в мокрое окно и страдать так, будто жизнь навсегда разбита?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'База на месте.',
      wrong: 'Фальшивая нота.',
    },
    answers: [
      { id: 'a', title: '«Одинокий голубь» (Яна)' },
      { id: 'b', title: '«Ветер с моря дул» (Натали)' },
      { id: 'c', title: '«Чашка кофию» (Марина Хлебникова)' },
      { id: 'd', title: '«Маленькая страна» (Наташа Королёва)' },
    ],
  },
  {
    id: 'm5',
    category: 'timeline',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой из этих хитов вышел уже в нулевых, а НЕ в 90-х?',
    correctAnswerId: 'd',
    feedback: {
      correct: 'Знаешь наизусть!',
      wrong: 'Срезалась!',
    },
    answers: [
      { id: 'a', title: '«Сэра»' },
      { id: 'b', title: '«Ветер с моря дул»' },
      { id: 'c', title: '«Мальчик хочет в Тамбов»' },
      { id: 'd', title: '«Я сошла с ума»' },
    ],
  },
  {
    id: 'm6',
    category: 'mismatch',
    difficulty: 'medium',
    layout: 'choice',
    title: 'В какой паре «исполнитель — песня» спрятана ошибка?',
    correctAnswerId: 'c',
    feedback: {
      correct: 'С первой ноты.',
      wrong: 'Мимо кассы.',
    },
    answers: [
      { id: 'a', title: 'Линда — «Ворона»' },
      { id: 'b', title: 'Андрей Губин — «Мальчик-бродяга»' },
      { id: 'c', title: 'Натали — «Мальчик хочет в Тамбов»' },
      { id: 'd', title: 'Технология — «Нажми на кнопку»' },
    ],
  },
  {
    id: 'm7',
    category: 'tv-culture',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какая легендарная пара вела «Бодрое утро» на MTV Россия, под шутки которых собирались в школу и институт?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Без шансов для ошибки.',
      wrong: 'Не угадала.',
    },
    answers: [
      { id: 'a', title: 'Яна Чурикова и Александр Анатольевич' },
      { id: 'b', title: 'Ольга Шелест и Антон Комолов' },
      { id: 'c', title: 'Тутта Ларсен и Вася Стрельников' },
      { id: 'd', title: 'Аврора и Лера Кудрявцева' },
    ],
  },
  {
    id: 'm8',
    category: 'pop-culture',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какой журнал в конце 90-х прятали под подушку от родителей ради постеров, анкет и честных ответов про мальчиков?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Красиво!',
      wrong: 'Рядом, но нет.',
    },
    answers: [
      { id: 'a', title: '«Ровесник»' },
      { id: 'b', title: '«Cool Girl»' },
      { id: 'c', title: '«Крестьянка»' },
      { id: 'd', title: '«Бурда Моден»' },
    ],
  },
  {
    id: 'm9',
    category: 'artist',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Что из этого — сценическое имя одного артиста, а не название группы?',
    correctAnswerId: 'c',
    feedback: {
      correct: 'Точно в ритм.',
      wrong: 'Память подвела.',
    },
    answers: [
      { id: 'a', title: 'Hi-Fi' },
      { id: 'b', title: 'Демо' },
      { id: 'c', title: 'Mr. Credo' },
      { id: 'd', title: 'Вирус!' },
    ],
  },
  {
    id: 'm10',
    category: 'producer',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Кто придумал мрачный стиль певицы Линды и написал музыку к «Вороне» и «Мало огня»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Память не подводит!',
      wrong: 'Слишком сложно?',
    },
    answers: [
      { id: 'a', title: 'Игорь Матвиенко' },
      { id: 'b', title: 'Максим Фадеев' },
      { id: 'c', title: 'Бари Алибасов' },
      { id: 'd', title: 'Юрий Айзеншпис' },
    ],
  },
  {
    id: 'm11',
    category: 'group-history',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какую девичью группу в конце 90-х называли «русскими Spice Girls», где у каждой солистки был свой образ — от «радистки» до пацанки?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Классика.',
      wrong: 'Не тот трек.',
    },
    answers: [
      { id: 'a', title: 'Блестящие' },
      { id: 'b', title: 'Стрелки' },
      { id: 'c', title: 'Лицей' },
      { id: 'd', title: 'Комбинация' },
    ],
  },
  {
    id: 'm12',
    category: 'absurd-description',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой хит «Иванушек» звучит как мем: «POV: на улице жара +30, а вокруг почему-то сугробы»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Как по нотам!',
      wrong: 'Обидно, но мимо.',
    },
    answers: [
      { id: 'a', title: '«Тучи»' },
      { id: 'b', title: '«Тополиный пух»' },
      { id: 'c', title: '«Кукла»' },
      { id: 'd', title: '«Снегири»' },
    ],
  },
  {
    id: 'm13',
    category: 'artist-image',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Чей сценический образ в 90-х запомнился всем: шуба на голое тело, платформы и полное отсутствие передних зубов?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Легчайшая.',
      wrong: 'Спутала!',
    },
    answers: [
      { id: 'a', title: 'Шура' },
      { id: 'b', title: 'Богдан Титомир' },
      { id: 'c', title: 'Никита' },
      { id: 'd', title: 'Кай Метов' },
    ],
  },
  {
    id: 'm14',
    category: 'music-video',
    difficulty: 'hard',
    layout: 'choice',
    title: 'В каком клипе 90-х тусуется богема, певицу похищают Бондарчук и Паук, а всё происходящее похоже на русский криминальный фильм?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Ни секунды сомнений!',
      wrong: 'Увы, не угадала.',
    },
    answers: [
      { id: 'a', title: 'Линда — «Ворона»' },
      { id: 'b', title: 'Лика Стар — «Одинокая луна»' },
      { id: 'c', title: 'Наталья Ветлицкая — «Посмотри в глаза»' },
      { id: 'd', title: 'Мумий Тролль — «Владивосток 2000»' },
    ],
  },
  {
    id: 'm15',
    category: 'absurd-description',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой хит 90-х сегодня подошёл бы на роль статуса в Telegram при расставании?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Золотой фонд.',
      wrong: 'Мимо нот.',
    },
    answers: [
      { id: 'a', title: '«Ты меня не ищи»' },
      { id: 'b', title: '«Позови меня с собой»' },
      { id: 'c', title: '«Беги от меня»' },
      { id: 'd', title: '«Плачь, плачь»' },
    ],
  },
  {
    id: 'm16',
    category: 'music-video',
    difficulty: 'hard',
    layout: 'choice',
    title: 'В каком клипе певица в серебристом мини-платье и с каре танцует в павильоне среди софитов и операторских рельсов?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Чистая победа.',
      wrong: 'Не попала в такт.',
    },
    answers: [
      { id: 'a', title: 'Лада Дэнс — «Девочка-ночь»' },
      { id: 'b', title: 'Наталья Ветлицкая — «Посмотри в глаза»' },
      { id: 'c', title: 'Татьяна Овсиенко — «Школьная пора»' },
      { id: 'd', title: 'Ирина Салтыкова — «Серые глаза»' },
    ],
  },
  {
    id: 'm17',
    category: 'artist-image',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой романтичный певец в 90-е убедил девчонок, что мальчикам тоже не стыдно страдать и плакать от любви?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Уровень: профи.',
      wrong: 'Ай, осечка!',
    },
    answers: [
      { id: 'a', title: 'Влад Сташевский' },
      { id: 'b', title: 'Андрей Губин' },
      { id: 'c', title: 'Кай Метов' },
      { id: 'd', title: 'Влад Топалов' },
    ],
  },
  {
    id: 'm18',
    category: 'era-culture',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Главный лайфхак школьных дискотек 90-х: на что ставили чёлку-каркас, если под рукой не было лака «Прелесть»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Абсолют!',
      wrong: 'Тут не срослось.',
    },
    answers: [
      { id: 'a', title: 'На пиво' },
      { id: 'b', title: 'На сахарную воду' },
      { id: 'c', title: 'На мыльную пену' },
      { id: 'd', title: 'На мучной клейстер' },
    ],
  },
  // --- 24 NEW QUESTIONS (Q19–Q42) ---
  {
    id: 'm19',
    category: 'rebus',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой хит зашифрован?\n\n☕️ 🫖 ❌ 💐 ❌ 💬',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Точно!',
      wrong: 'Мимо.',
    },
    answers: [
      { id: 'a', title: '«Какао-какао»' },
      { id: 'b', title: '«Чашка кофию»' },
      { id: 'c', title: '«Зимний сон»' },
      { id: 'd', title: '«Малыш»' },
    ],
  },
  {
    id: 'm20',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Кому в танцевальном гимне 1999 года принадлежал крик: «Ну где же ваши ручки, девчонки и мальчики»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Зачёт!',
      wrong: 'Не-а, мимо.',
    },
    answers: [
      { id: 'a', title: 'Группа «Демо»' },
      { id: 'b', title: 'Группа «Вирус!»' },
      { id: 'c', title: '«Руки Вверх!»' },
      { id: 'd', title: '«Стрелки»' },
    ],
  },
  {
    id: 'm21',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Кто в хите «Руки Вверх!» бесстыдно целует девчонку и «к сердцу прижимает» вместо главного героя?',
    correctAnswerId: 'c',
    feedback: {
      correct: 'В яблочко!',
      wrong: 'Почти.',
    },
    answers: [
      { id: 'a', title: 'Старший брат' },
      { id: 'b', title: 'Студент' },
      { id: 'c', title: 'Чужие губы' },
      { id: 'd', title: 'Лучший друг' },
    ],
  },
  {
    id: 'm22',
    category: 'clip',
    difficulty: 'medium',
    layout: 'choice',
    title: 'В каком клипе юная Алсу бродит по заснеженному дому и страдает по взрослому герою Сергея Маковецкого?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Память работает.',
      wrong: 'Мимо кассы.',
    },
    answers: [
      { id: 'a', title: '«Иногда»' },
      { id: 'b', title: '«Зимний сон»' },
      { id: 'c', title: '«Свет в твоём окне»' },
      { id: 'd', title: '«Осень»' },
    ],
  },
  {
    id: 'm23',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой поп-рок хит 1998 года превратил детское стихотворение Агнии Барто в главный альтернативный гимн дискотек?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Красиво!',
      wrong: 'Не тот трек.',
    },
    answers: [
      { id: 'a', title: '«Любочка» («Маша и Медведи»)' },
      { id: 'b', title: '«Ромашки» (Земфира)' },
      { id: 'c', title: '«Орбит без сахара» («Сплин»)' },
      { id: 'd', title: '«Ты кинула» («Ляпис Трубецкой»)' },
    ],
  },
  {
    id: 'm24',
    category: 'song',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Что, согласно песне Татьяны Овсиенко, «в речке утонуло» вместе с девичьими надеждами?',
    correctAnswerId: 'c',
    feedback: {
      correct: 'Да!',
      wrong: 'Ай, осечка.',
    },
    answers: [
      { id: 'a', title: 'Письмо' },
      { id: 'b', title: 'Фотография' },
      { id: 'c', title: 'Колечко' },
      { id: 'd', title: 'Сердечко' },
    ],
  },
  {
    id: 'm25',
    category: 'mtv',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Кто вёл культовый «News Блок» на MTV Россия бархатным баритоном с коронной фразой: «Пока, я — ...»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Точно в цель!',
      wrong: 'Не угадала.',
    },
    answers: [
      { id: 'a', title: 'Антон Комолов' },
      { id: 'b', title: 'Александр Анатольевич' },
      { id: 'c', title: 'Василий Стрельников' },
      { id: 'd', title: 'Михаил Роллер' },
    ],
  },
  {
    id: 'm26',
    category: 'clip',
    difficulty: 'hard',
    layout: 'choice',
    title: 'В каком клипе 90-х в кинозале собрались повзрослевшие звёзды комедии «Иван Васильевич меняет профессию»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Как по нотам!',
      wrong: 'Память подвела.',
    },
    answers: [
      { id: 'a', title: '«Сказочная тайга» («Агата Кристи»)' },
      { id: 'b', title: '«Как на войне» («Агата Кристи»)' },
      { id: 'c', title: '«Ковёр-вертолёт» («Агата Кристи»)' },
      { id: 'd', title: '«Скованные одной цепью» («Nautilus Pompilius»)' },
    ],
  },
  {
    id: 'm27',
    category: 'mtv',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Культовая передача на MTV Россия, где зрители в студии в пух и прах разносили свежие клипы артистов:',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Классика.',
      wrong: 'Рядом, но нет.',
    },
    answers: [
      { id: 'a', title: '«12 злобных зрителей»' },
      { id: 'b', title: '«Акулы пера»' },
      { id: 'c', title: '«Башня»' },
      { id: 'd', title: '«До 16 и старше»' },
    ],
  },
  {
    id: 'm28',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой трек группы Hi-Fi в 1998 году гремел строчками: «...тебе закрыть эту дверь, остаться здесь и не жить»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Золотой фонд.',
      wrong: 'Фальшивая нота.',
    },
    answers: [
      { id: 'a', title: '«Беспризорник»' },
      { id: 'b', title: '«Не дано»' },
      { id: 'c', title: '«Глупые люди»' },
      { id: 'd', title: '«Чёрный ворон»' },
    ],
  },
  {
    id: 'm29',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какую фразу хриплым полушёпотом повторял Кай Метов в припеве своего суперхита 1993 года?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'В точку!',
      wrong: 'Эх, мимо.',
    },
    answers: [
      { id: 'a', title: '«Position Number One»' },
      { id: 'b', title: '«Position Number Two»' },
      { id: 'c', title: '«Come on, everybody»' },
      { id: 'd', title: '«Baby tonight»' },
    ],
  },
  {
    id: 'm30',
    category: 'artist',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Кто была солисткой и писала тексты песен в группе «Гости из будущего»?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Чистая победа.',
      wrong: 'Срезалась!',
    },
    answers: [
      { id: 'a', title: 'Лика Стар' },
      { id: 'b', title: 'Ева Польна' },
      { id: 'c', title: 'Саша Зверева' },
      { id: 'd', title: 'Света' },
    ],
  },
  {
    id: 'm31',
    category: 'song',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какая группа в декабре 1999 года подарила стране гимн школьных дискотек со словами: «Новый год к нам мчится, скоро всё случится»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Точно в ритм.',
      wrong: 'Мимо нот.',
    },
    answers: [
      { id: 'a', title: '«Дискотека Авария»' },
      { id: 'b', title: '«Стрелки»' },
      { id: 'c', title: '«Отпетые Мошенники»' },
      { id: 'd', title: '«Руки Вверх!»' },
    ],
  },
  {
    id: 'm32',
    category: 'artist',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какой певец покорил хит-парады 90-х, выступая босиком, с кудрями до плеч и песней про «Босоногого мальчика»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Абсолют!',
      wrong: 'Тут не срослось.',
    },
    answers: [
      { id: 'a', title: 'Леонид Агутин' },
      { id: 'b', title: 'Владимир Пресняков' },
      { id: 'c', title: 'Игорь Николаев' },
      { id: 'd', title: 'Влад Сташевский' },
    ],
  },
  {
    id: 'm33',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой предмет гардероба Валерий Сюткин в составе «Браво» воспевал как символ стиля назло серой толпе?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'База на месте.',
      wrong: 'Не попала в такт.',
    },
    answers: [
      { id: 'a', title: 'Стильный оранжевый галстук' },
      { id: 'b', title: 'Малиновый пиджак' },
      { id: 'c', title: 'Жёлтые ботинки' },
      { id: 'd', title: 'Кожаную косуху' },
    ],
  },
  {
    id: 'm34',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Под какой медляк «Отпетых Мошенников» 1999 года школьники танцевали на дискотеках, хором повторяя: «...жарким огнём, ночью и днём»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Уровень: профи.',
      wrong: 'Обидно, но мимо.',
    },
    answers: [
      { id: 'a', title: '«Люби меня, люби»' },
      { id: 'b', title: '«Всяко-разно»' },
      { id: 'c', title: '«Бросай курить»' },
      { id: 'd', title: '«Я учусь танцевать»' },
    ],
  },
  {
    id: 'm35',
    category: 'clip',
    difficulty: 'hard',
    layout: 'choice',
    title: 'В каком клипе «Мумий Тролля» 1997 года Илья Лагутенко ножницами беспощадно стриг девушку?',
    correctAnswerId: 'b',
    feedback: {
      correct: 'Ни секунды сомнений!',
      wrong: 'Увы, не угадала.',
    },
    answers: [
      { id: 'a', title: '«Владивосток 2000»' },
      { id: 'b', title: '«Утекай»' },
      { id: 'c', title: '«Дельфины»' },
      { id: 'd', title: '«Кот кота»' },
    ],
  },
  {
    id: 'm36',
    category: 'culture',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Как в школьных анкетах 90-х обычно называли страницу, которую складывали треугольником и строго запрещали открывать?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Легчайшая.',
      wrong: 'Спутала!',
    },
    answers: [
      { id: 'a', title: '«Секрет»' },
      { id: 'b', title: '«Тайник»' },
      { id: 'c', title: '«Сюрприз»' },
      { id: 'd', title: '«Загадка»' },
    ],
  },
  {
    id: 'm37',
    category: 'rebus',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Какой хит зашифрован?\n\n🌬️ 🌊 💨 💔',
    correctAnswerId: 'a',
    feedback: {
      correct: 'С первой ноты.',
      wrong: 'Мимо кассы.',
    },
    answers: [
      { id: 'a', title: '«Ветер с моря дул»' },
      { id: 'b', title: '«Холодная луна»' },
      { id: 'c', title: '«Тучи»' },
      { id: 'd', title: '«Зимняя вишня»' },
    ],
  },
  {
    id: 'm38',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Под какую строчку летом 1999 года школьники встречали рассветы на выпускных по всей стране?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Знаешь наизусть!',
      wrong: 'Не-а, не то.',
    },
    answers: [
      { id: 'a', title: '«Солнышко в руках и венок из звёзд в небесах»' },
      { id: 'b', title: '«Ветер с моря дул, нагонял беду»' },
      { id: 'c', title: '«Ты бросил меня, ты бросил меня»' },
      { id: 'd', title: '«Люби меня, люби, жарким огнём»' },
    ],
  },
  {
    id: 'm39',
    category: 'artist',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какой артист в свитере и с гитарой заставил всю страну в начале 90-х подпевать «Плачет девушка в автомате»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Память не подводит!',
      wrong: 'Чуть-чуть не туда.',
    },
    answers: [
      { id: 'a', title: 'Евгений Осин' },
      { id: 'b', title: 'Сергей Крылов' },
      { id: 'c', title: 'Кай Метов' },
      { id: 'd', title: 'Виктор Салтыков' },
    ],
  },
  {
    id: 'm40',
    category: 'song',
    difficulty: 'medium',
    layout: 'choice',
    title: 'Как официально называется прорывной хит Земфиры 1999 года со строчками про «трещинки» и обещанием «убить соседей, что мешают спать»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Без шансов для ошибки.',
      wrong: 'Не угадала.',
    },
    answers: [
      { id: 'a', title: '«Ариведерчи»' },
      { id: 'b', title: '«Трещинки»' },
      { id: 'c', title: '«Соседи»' },
      { id: 'd', title: '«Ромашки»' },
    ],
  },
  {
    id: 'm41',
    category: 'artist',
    difficulty: 'easy',
    layout: 'choice',
    title: 'Какая девичья группа с гитарами взорвала хит-парады 1995 года песней: «Осень, осень, лес остыл и листья сбросил»?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Красиво!',
      wrong: 'Рядом, но нет.',
    },
    answers: [
      { id: 'a', title: '«Лицей»' },
      { id: 'b', title: '«Блестящие»' },
      { id: 'c', title: '«Стрелки»' },
      { id: 'd', title: '«Комбинация»' },
    ],
  },
  {
    id: 'm42',
    category: 'culture',
    difficulty: 'medium',
    layout: 'choice',
    title: 'В каком культовом фильме певица Ирина Салтыкова сыграла саму себя и закрутила роман с главным героем?',
    correctAnswerId: 'a',
    feedback: {
      correct: 'Точно!',
      wrong: 'Мимо.',
    },
    answers: [
      { id: 'a', title: '«Брат 2»' },
      { id: 'b', title: '«Брат»' },
      { id: 'c', title: '«Улицы разбитых фонарей»' },
      { id: 'd', title: '«Мама, не горюй»' },
    ],
  },
]

// Canonical 42-question bank alias (bank === questions)
export const music90sBank = questions

/** Approved Music90s definition, validated by loadQuiz() before use. */
export const music90sQuiz: Quiz = {
  id: 'music90s',
  title: 'Ты точно помнишь музыку 90-х?',
  subtitle: '18 вопросов о хитах, клипах и той самой жизни в 90-х.',
  landing: {
    paragraphs: [
      'Кассеты перематывали карандашом, а хиты знали наизусть.',
      'Восемнадцать вопросов — и станет ясно, где ты была в 1999-м: на дискотеке или в своей комнате.',
      'Отвечай быстро, не гугли.',
    ],
    meta: ['18 вопросов', 'около 4 минут'],
  },
  startCta: 'Проверить память',
  shareCtaIntro: 'Пусть попробуют побить твой счёт ↓',
  shareCta: 'Бросить вызов',
  restartCta: 'Пройти ещё раз',
  channelPromotion: {
    authorName: 'Бюро историй',
    landingAttribution: 'тест от Бюро историй',
    resultIntro: 'Я в канале иногда собираю похожие штуки и просто делюсь историями. Заглядывай.',
    resultCta: 'Зайти в Бюро историй →',
    shareFooter: {
      title: 'Бюро историй',
      handle: '@takeiteasybefore',
    },
    destinations: {
      telegram: { url: 'https://t.me/takeiteasybefore' },
      max: { url: 'https://max.ru/takeiteasybefore' },
    },
  },
  share: {
    assetPrefix: 'm90',
    assetVersion: 'v4',
  },
  copy: {
    eyebrow: 'музыкальный тест',
    shareHeadline: 'Ты точно помнишь музыку 90-х? Проверь себя:',
    deliverOwnLine: 'Это твой счёт по музыке 90-х ✨',
  },
  questions,
  results,
  scoring: {
    kind: 'correct-count',
    bands: [
      { min: 0, max: 4, resultId: 'm90_rookie' },
      { min: 5, max: 7, resultId: 'm90_familiar' },
      { min: 8, max: 10, resultId: 'm90_cassette' },
      { min: 11, max: 13, resultId: 'm90_disco' },
      { min: 14, max: 16, resultId: 'm90_legend' },
      { min: 17, max: 17, resultId: 'm90_era17' },
      { min: 18, max: 18, resultId: 'm90_era18' },
    ],
  },
  presentation: { kind: 'score' },
  answerBehavior: { mode: 'feedback', durationMs: 900, correctMessage: 'Верно.', wrongMessage: 'Не угадала.' },
  reveal: {
    steps: ['Кассеты', 'Диски', 'Твой счёт'],
    stepDurationMs: 250,
  },
}
